language: java
dist: trusty
jdk:
- oraclejdk8 
addons:
  sonarqube:
    token: ukuP+huxJDpsLyGmY5SZ97Xq1K+1tpMPvzakG51T4eNZdbhupJG0PCYsmaLIV/t1ZX7AUUjayZld3wc/H4zTa/t4RsUnggJo94Lv3zU7bAFqH5sS8SduvlLRtF3Vqd428kuMum9tcdp6l+0jSdSKo+RSzeHeis+H0dzoSMMkFgjFxHHScab4Uv+qsWiBC4Opwh36TyfJuZfUcc10S4+Q7SMzT47ffSF3vbmDnUcdPMP7BJteiqcmh/pp9wQI9/XjaIJVzPFmcmhd9AMtG4ZM0Q/gegYPkFsMZ3e9RguiZHmdvxsi0DvfZOmKY8jcPobOhEJrKA40BvW3w8vN1r30GH8QnHOYC6NRkAuSOcdSCmt2hzyONE5BPkQRA2slfC4oYJRd45VdQCB/jkP+pZB0EKqZE4zjBCHkKrcyLwKfsy1HkS7owrmbCQa9KE1p5tasy7LuC4jh6dgOSuUWDrxXGdnIKIXB6GtqSKkdb16xD0+R2GoQ8dEvJRR51Dc3EbR/J0IzS1J4aTVK1Y3TUjt62o/URqZIfAcCfK2Zt8GN+YQzHQRQDjf1lZxzDT8s1RiUZSprBeeHkjhKii5kwYPZAiSj1STtW3ePqht8bh0Yf060RwxJ18KfDOKFG3WjXocVO6t44iYbrDG5qepZAYJ9m471VaZP6sMaYJLZ++MsoQI=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar