language: java
script:
- mvn test
jdk:
- oraclejdk8 
env:
  global:
    secure: X5kiCdzEP3hEaMy1eJcYUnwr8IfPKr46WBigc561Su65zOPP9aEOmKI08K8Pe7JbYZ9Ut1jdNb9/mxxfEgty4gGllMwETekpy1UUko0gKKMdAt5OmXKHzKdihiBFMcLPn0eGoD9U4A26AhJ7epXTDWk7SJJTxhKq+RmZXlJpOXHLltj4tNuL4t8l5u0eHFwjSNtkI1nNSwQQQRsU/aDOrqyi2r4vR8xHG2ZCcsqqp0ghFVOsaltTydMq3qKLLPXhvv5FyIUNW1Ljqu2kQ+qT3NpaiKM/Q7EEtWNz39GoHCmQuDRnflmh184wHZCnlrgNJEx+zLEcqTph2Knt3Bh1sCHvuVPf4WD6C1U3Kp1LL64cvDtXrxZ6V5RLEkml2hqzwOQkIe75TK7ZDpYckECOypeo2h92zJZXtBG6x9Icl4zoEcGMjJueSeUTMGrL164nO1AyOvdMYzkqwyKXlNadPY6yWDRum+krTxuEfZQ/T2yZr4BCdf3XpftQlWZDebC4wx//E2UPZcgmQQZ4Lmtsf2Dw6mRvS8WPZVB7LzP5ioLKAn8hZjVP8jVpbfe0Dl7TkTyfTxtNgsHb18bQxGixY3c9P7nJyKYd8+2VZtV0URflLHr4XLcvJgAds5g0IpQ/u9XqHVIsyGgIkAt19NU7sqf0qm5M9nuCKpnEGbV9Xkc=
script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner