language: java
dist: trusty
jdk:
- oraclejdk8 
addons:
  sonarqube:
    organization: "juliogb"
    token: 
      secure: "CvZn80EM8iiD3WR+SkYoqHww6EIWNX0MS5U2YwfIXRQnobaA6pq8Tpk/ajrDfrJZP90MKXE8/pivuiN1jDNnk/ROIlgDa3ztTypwZH1kfFImDmg9nbXEHHilv6Gi8FHyF3tN9Zw81OFKFX82RWK0GWte2LZhzqQTSb7sdOTu3m67LAalIxUcsjEm8hlcDPtRorH4ibytbRnn4LtGuxLKZ8i48DU9FQjLy/cB/S3GGcWT5dPhKrBTc2z2h4deh3QzRGvMaHUH42ViGbzZ3slNNE35p/zm4HLL0gsfO15Yg8dLdtTkdZQOD5FR/jKfiY+IJpeiMM8j7Dx1uJFwUoW9dyIhLKYG9v5FSmsETm/hu+MmOn6h9ODm4s8KfQhQvxu808ou8hSO4SlQP9MCe3qShrY7x8+0mzZfiCmPcticzgC0r84cxiT69YZDOAk2v0LG7xoDm84YLmUu23ivSGCyZGmEp1QJoOzLrpLUCKejPtyc7oG5gXrYcNoMQQ2Tij8kImJMmdECSoCnnKshjWc4hPE7tlG05uBQHWuVAY31XMXwaODDYXdAy42K01T/AmjirVgrxmtK5jliIFzLBKdfJpkShIDsZ+2iF7BQZZnnpZvpVFdRtjnozwSlfQl+sVbzDJno3SKnXdOCnSIcAxUwm/IyFV0sNqbVPyIJwZeHeO0="
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'